const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');

const root = join(__dirname, '..');
const manifest = JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8'));

assert.equal(manifest.manifest_version, 3);
assert.equal(manifest.background.service_worker, 'src/background.js');
assert.deepEqual(manifest.permissions.sort(), ['clipboardWrite', 'storage']);
assert.ok(!JSON.stringify(manifest).includes('<all_urls>'));
assert.ok(!JSON.stringify(manifest).includes('webRequest'));
assert.ok(!JSON.stringify(manifest).includes('debugger'));
assert.ok(!JSON.stringify(manifest.host_permissions).includes('http://*/*'));
assert.ok(!JSON.stringify(manifest).includes('tabs'));
assert.deepEqual(manifest.optional_host_permissions.sort(), ['http://*/*', 'https://*/*']);
assert.ok(manifest.content_scripts[0].matches.every((match) => match.includes('rocketscooter.com')));
assert.equal(manifest.content_scripts[0].run_at, 'document_start');
assert.match(JSON.stringify(manifest.web_accessible_resources), /src\/capture-rules\.js/);
assert.match(JSON.stringify(manifest.web_accessible_resources), /src\/page-hook\.js/);

const contentScript = readFileSync(join(root, 'src', 'content-script.js'), 'utf8');
const pageHook = readFileSync(join(root, 'src', 'page-hook.js'), 'utf8');
const background = readFileSync(join(root, 'src', 'background.js'), 'utf8');
const popup = readFileSync(join(root, 'src', 'popup.js'), 'utf8');
const popupHtml = readFileSync(join(root, 'src', 'popup.html'), 'utf8');
const popupCss = readFileSync(join(root, 'src', 'popup.css'), 'utf8');
const options = readFileSync(join(root, 'src', 'options.js'), 'utf8');
const optionsHtml = readFileSync(join(root, 'src', 'options.html'), 'utf8');
const optionsCss = readFileSync(join(root, 'src', 'options.css'), 'utf8');

assert.match(contentScript, /capture-rules\.js/);
assert.match(contentScript, /page-hook\.js/);
assert.match(contentScript, /rsLevelsNonce/);
assert.match(contentScript, /window\.location\.origin/);
assert.match(contentScript, /rs-levels\.capture-diagnostic/);
assert.match(pageHook, /NONCE/);
assert.match(pageHook, /event\.origin/);
assert.match(pageHook, /xhr\.responseType/);
assert.match(pageHook, /isTextLikeContentType/);
assert.match(pageHook, /observedCount/);
assert.match(pageHook, /ignoredCount/);
assert.match(pageHook, /skippedEmptyCount/);
assert.doesNotMatch(contentScript + pageHook, /document\.body\.innerText/);
assert.doesNotMatch(contentScript + pageHook, /document\.documentElement\.innerText/);
assert.doesNotMatch(background, /chrome\.cookies/);
assert.match(background, /importScripts\('shared\.js'\)/);
assert.match(background, /\/capture\/api/);
assert.match(background, /cleanCaptureStats/);
assert.match(popup, /\/tradingview\/\$\{selectedSymbol\(\)\}/);
assert.match(popup, /format=json/);
assert.match(popup, /\/diagnostics/);
assert.match(popup, /\/plugins/);
assert.match(popup, /copyTradingView/);
assert.match(popup, /cleanExtensionState/);
assert.match(popup, /renderCaptureStats/);
assert.match(popup, /toggleCapture/);
assert.match(popup, /renderTradingViewCopy/);
assert.match(popup, /tradingViewCopyIssue/);
assert.match(popup, /selectedSymbolIssue/);
assert.match(popup, /serviceVersion/);
assert.match(popup, /copyTv\.disabled/);
assert.match(popup, /copyJson\.disabled/);
assert.match(popup, /Captured levels are stale/);
assert.match(popupHtml, /copy-diagnostics/);
assert.match(popupHtml, /open-docs/);
assert.match(popupHtml, /open-plugins/);
assert.match(popupHtml, /capture-enabled/);
assert.match(popupHtml, /observed-count/);
assert.match(popupHtml, /ignored-count/);
assert.match(popupHtml, /skipped-count/);
assert.match(popupHtml, /service-version/);
assert.match(popupCss, /\.pill\.warning/);
assert.match(popupCss, /\.switch/);
assert.match(readFileSync(join(root, 'src', 'capture-rules.js'), 'utf8'), /isTextLikeContentType/);
assert.match(options, /chrome\.permissions\.request/);
assert.match(options, /chrome\.permissions\.contains/);
assert.match(options, /testService/);
assert.match(options, /fetchHealth/);
assert.match(options, /\/health/);
assert.match(options, /AbortController/);
assert.match(options, /permissionStatus/);
assert.match(optionsHtml, /test-service/);
assert.match(optionsHtml, /permission-status/);
assert.match(optionsCss, /\.status\.warning/);

console.log('browser extension static tests passed');
