const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');

const pine = readFileSync(join(__dirname, '..', 'rs-levels.pine'), 'utf8');
const varis = readFileSync(join(__dirname, '..', 'varis-zones.pine'), 'utf8');

assert.match(pine, /indicator\("RS Levels"/);
assert.doesNotMatch(pine, /\bstrategy\s*\(/i);
assert.doesNotMatch(pine, /\bstrategy\./i);
assert.doesNotMatch(pine, new RegExp('\\b' + 'ord' + 'er' + '\\b', 'i'));
assert.doesNotMatch(pine, /\balertcondition\s*\(/i);
assert.doesNotMatch(pine, /\brequest\./i);
assert.doesNotMatch(pine, /^\s*text\s*=/m);
assert.match(pine, /payload = input\.string\("", "RS Levels Payload", display = display\.none\)/);
assert.doesNotMatch(pine, /input\.text_area/);
assert.match(pine, /chartFamilyInput = input\.string\("Auto", "Chart family"/);
assert.match(pine, /options = \["Auto", "ES", "NQ"\]/);
assert.match(pine, /showStatsPanel = input\.bool\(true, "Stats panel"\)/);
assert.doesNotMatch(pine, /showStatus/);
assert.doesNotMatch(pine, /drawStatus/);
assert.doesNotMatch(pine, /statusText/);
assert.match(pine, /fontSizeInput = input\.string\("Small", "Font size"/);
assert.match(pine, /options = \["Tiny", "Small", "Normal", "Large", "Huge"\]/);
assert.match(pine, /labelSize/);
assert.match(pine, /"Tiny" => size\.tiny/);
assert.match(pine, /"Huge" => size\.huge/);
assert.match(pine, /size = labelSize\(\)/);
assert.match(pine, /displayLabelName/);
assert.match(pine, /str\.contains\(upperName, "OPEN"\)/);
assert.match(pine, /str\.replace_all\(name,\s*"horizontal_line",\s*""\)/);
assert.match(pine, /str\.replace_all\(cleaned,\s*"HORIZONTAL_LINE",\s*""\)/);
assert.match(pine, /compactUpper == "LINE"/);
assert.match(pine, /str\.replace_all\(cleaned, "Liquidity Map", ""\)/);
assert.match(pine, /labelText = displayLabelName\(name, effectiveKind\)/);
assert.match(pine, /labelBarsOffset/);
assert.match(pine, /labelVerticalOffset/);
assert.match(pine, /"Min label vertical offset \(ticks\)"/);
assert.match(pine, /chart\.left_visible_bar_time/);
assert.match(pine, /chart\.right_visible_bar_time/);
assert.match(pine, /visibleBarRange/);
assert.match(pine, /labelStackRows = 6/);
assert.match(pine, /labelStackColumnBars = 4/);
assert.match(pine, /labelDirection/);
assert.match(pine, /"mhp" => -1/);
assert.match(pine, /labelStackRow/);
assert.match(pine, /labelStackColumn/);
assert.match(pine, /labelX/);
assert.match(pine, /labelOffset/);
assert.match(pine, /labelPrice/);
assert.match(pine, /rangeOffset = math\.max\(priceRange, syminfo\.mintick\) \* 0\.0045 \* stackMultiplier/);
assert.match(pine, /labelY = labelPrice\(name, effectiveKind, price, labelIndex, priceRange\)/);
assert.match(pine, /label\.new\(labelX\(labelIndex\), labelY,/);
assert.doesNotMatch(pine, /label\.new\(bar_index \+ labelBarsOffset, price,/);
assert.doesNotMatch(pine, /compactPayload/);
assert.match(pine, /RSLEVELS/);
assert.match(pine, /chartPayloadSymbol/);
assert.match(pine, /payloadCompact/);
assert.match(pine, /payloadSymbolLevelText/);
assert.match(pine, /var table rsStatsTable = table\.new\(position\.bottom_left, 1, 2\)/);
assert.match(pine, /cleanKind\(kind\) =>/);
assert.match(pine, /str\.lower\(str\.replace_all\(kind, " ", ""\)\)/);
assert.match(pine, /levelKind\(name, kind\) =>/);
assert.match(pine, /str\.contains\(upperName, "RED LINE"\) or str\.startswith\(upperName, "RL"\)/);
assert.match(pine, /str\.contains\(upperName, "YELLOW LINE"\) or str\.startswith\(upperName, "YL"\)/);
assert.match(pine, /str\.contains\(upperName, "CAT"\)/);
assert.match(pine, /statValue/);
assert.match(pine, /statsPanelBody/);
assert.match(pine, /drawStatsPanel/);
assert.match(pine, /normalizedKind == "stat"/);
assert.match(pine, /"stat" => false/);
assert.match(pine, /table\.cell\(rsStatsTable, 0, 0/);
assert.match(pine, /table\.cell\(rsStatsTable, 0, 1/);
assert.match(pine, /appendStatText\(lineText, "DD"/);
assert.match(pine, /appendStatText\(lineText, "RI"/);
assert.match(pine, /appendStatText\(lineText, "Res"/);
assert.match(pine, /appendStatText\(lineText, "MRes"/);
assert.match(pine, /appendStatText\(lineText, "WRes"/);
assert.match(pine, /"  Map " \+ mapText/);
assert.match(pine, /str\.split\(payloadCompact\(payloadText\), "\|"\)/);
assert.match(pine, /array\.get\(parts, 0\) == "RSLEVELS"/);
assert.match(pine, /array\.get\(parts, 1\) == "2"/);
assert.match(pine, /for sectionIndex = 3 to array\.size\(parts\) - 3 by 3/);
assert.match(pine, /bestPayloadLevelText/);
assert.match(pine, /rootText == "NQ"/);
assert.match(pine, /rootText == "ES"/);
assert.match(pine, /str\.startswith\(tickerText, "MNQ"\)/);
assert.match(pine, /str\.startswith\(tickerText, "MES"\)/);
assert.match(pine, /str\.contains\(tickerIdText, ":NQ"\)/);
assert.match(pine, /str\.contains\(tickerIdText, ":ES"\)/);
assert.match(pine, /chartSymbol == "ES"/);
assert.match(pine, /chartSymbol == "NQ"/);
assert.match(pine, /esLevelText != "" and nqLevelText == ""/);
assert.match(pine, /levelTextForChart/);
assert.doesNotMatch(pine, /tradingview-bundle-json/);
assert.doesNotMatch(pine, /tradingview-json/);
assert.doesNotMatch(pine, /json/i);
assert.match(pine, /syminfo\.root/);
assert.match(pine, /syminfo\.tickerid/);
assert.match(pine, /syminfo\.description/);
assert.doesNotMatch(pine, /math\.abs\(price - close\)/);
assert.doesNotMatch(pine, /while sectionIndex \+ 2 < array\.size\(parts\)/);
assert.doesNotMatch(pine, /fallbackSymbol/);
assert.match(pine, /str\.split/);
assert.match(pine, /showDdBands/);
assert.match(pine, /showHp/);
assert.match(pine, /showBullZones/);
assert.match(pine, /showBearZones/);
assert.match(pine, /showYellowLines/);
assert.match(pine, /showRedLines/);
assert.match(pine, /showCatLines/);
assert.match(pine, /showZoneFills = input\.bool\(true, "Zone fills"\)/);
assert.doesNotMatch(pine, /showUnknown/);
assert.doesNotMatch(pine, /\bshowZones\b/);
assert.doesNotMatch(pine, /genericZoneColorInput/);
assert.match(pine, /zoneFillOpacityInput = input\.int\(12, "Zone fill opacity %"/);
assert.match(pine, /showDdBands = input\.bool\(true, "DD bands", inline = "dd"\)/);
assert.match(pine, /ddBandColorInput = input\.color\(color\.rgb\(0, 188, 212\), "", inline = "dd"\)/);
assert.match(pine, /showHp = input\.bool\(true, "HP", inline = "hp"\)/);
assert.match(pine, /hpColorInput = input\.color\(color\.rgb\(41, 98, 255\), "", inline = "hp"\)/);
assert.match(pine, /showMhp = input\.bool\(true, "MHP", inline = "mhp"\)/);
assert.match(pine, /mhpColorInput = input\.color\(color\.rgb\(255, 152, 0\), "", inline = "mhp"\)/);
assert.match(pine, /showOpenClose = input\.bool\(true, "Open\/close", inline = "openClose"\)/);
assert.match(pine, /openCloseColorInput = input\.color\(color\.rgb\(255, 255, 255\), "", inline = "openClose"\)/);
assert.match(pine, /showReference = input\.bool\(true, "References", inline = "reference"\)/);
assert.match(pine, /referenceColorInput = input\.color\(color\.rgb\(255, 235, 59\), "", inline = "reference"\)/);
assert.match(pine, /showYellowLines = input\.bool\(true, "Yellow lines", inline = "yellowLine"\)/);
assert.match(pine, /yellowLineColorInput = input\.color\(color\.rgb\(255, 235, 59\), "", inline = "yellowLine"\)/);
assert.match(pine, /showRedLines = input\.bool\(true, "Red lines", inline = "redLine"\)/);
assert.match(pine, /redLineColorInput = input\.color\(color\.rgb\(242, 54, 69\), "", inline = "redLine"\)/);
assert.match(pine, /showCatLines = input\.bool\(true, "CAT lines", inline = "catLine"\)/);
assert.match(pine, /catLineColorInput = input\.color\(color\.rgb\(126, 87, 194\), "", inline = "catLine"\)/);
assert.match(pine, /showBullZones = input\.bool\(true, "Bull zones", inline = "bullZone"\)/);
assert.match(pine, /bullZoneColorInput = input\.color\(color\.rgb\(76, 175, 80\), "", inline = "bullZone"\)/);
assert.match(pine, /showBearZones = input\.bool\(true, "Bear zones", inline = "bearZone"\)/);
assert.match(pine, /bearZoneColorInput = input\.color\(color\.rgb\(240, 98, 146\), "", inline = "bearZone"\)/);
assert.match(pine, /showOtherLevels = input\.bool\(true, "Other levels", inline = "otherLevels"\)/);
assert.match(pine, /otherLevelColorInput = input\.color\(color\.rgb\(158, 158, 158\), "", inline = "otherLevels"\)/);
assert.match(pine, /showDdBands[\s\S]*ddBandColorInput/);
assert.match(pine, /showHp[\s\S]*hpColorInput/);
assert.match(pine, /showBearZones[\s\S]*bearZoneColorInput/);
assert.doesNotMatch(pine, /group = "Level colors"/);
assert.doesNotMatch(pine, /unknownColorInput/);
assert.match(pine, /"zone-bull"/);
assert.match(pine, /"zone-bear"/);
assert.match(pine, /"zone-bull" => bullZoneColorInput/);
assert.match(pine, /"zone-bear" => bearZoneColorInput/);
assert.match(pine, /"yellow-line" => yellowLineColorInput/);
assert.match(pine, /"red-line" => redLineColorInput/);
assert.match(pine, /"cat" => catLineColorInput/);
assert.match(pine, /"yellow-line" => showYellowLines/);
assert.match(pine, /"red-line" => showRedLines/);
assert.match(pine, /"cat" => showCatLines/);
assert.match(pine, /effectiveKind = levelKind\(name, kind\)/);
assert.match(pine, /kindEnabled\(effectiveKind\)/);
assert.match(pine, /levelColor = kindColor\(effectiveKind\)/);
assert.match(pine, /line\.new\(bar_index - 1, price, bar_index, price, extend = extend\.both, color = levelColor/);
assert.match(pine, /label\.new\(labelX\(labelIndex\), labelY, labelText[\s\S]*textcolor = levelColor/);
assert.match(pine, /"CAT"/);
assert.match(pine, /"Yellow Line"/);
assert.match(pine, /"Red Line"/);
assert.doesNotMatch(pine, /"zone" =>/);
assert.doesNotMatch(pine, /kind == "zone"/);
assert.match(pine, /"hp" => hpColorInput/);
assert.match(pine, /=> otherLevelColorInput/);
assert.match(pine, /=> showOtherLevels/);
assert.match(pine, /max_boxes_count = 500/);
assert.match(pine, /array\.new_box\(\)/);
assert.match(pine, /box\.delete\(array\.pop\(rsBoxes\)\)/);
assert.match(pine, /zoneBoundarySide/);
assert.match(pine, /str\.contains\(upperName, "BZT"\)/);
assert.match(pine, /str\.contains\(upperName, "BRZB"\)/);
assert.match(pine, /drawZoneFill/);
assert.match(pine, /drawZoneFills\(levelText, maxCount\)/);
assert.match(pine, /levelPriceRange\(levelText, maxCount\)/);
assert.match(pine, /priceRange = math\.max\(visibleBarRange, levelPriceRange\(levelText, maxCount\)\)/);
assert.match(pine, /box\.new\(left = bar_index - 1/);
assert.match(pine, /bgcolor = color\.new\(zoneColor, fillTransparency\)/);
assert.match(pine, /lineStyleInput/);
assert.match(pine, /maxLevelsInput/);
assert.match(pine, /max_lines_count = 500/);
assert.match(pine, /max_labels_count = 500/);
assert.match(pine, /maxval = 500/);
assert.match(pine, /drawStatsPanel\(levelText\)/);
assert.doesNotMatch(pine, /label\.style_label_down/);

assert.match(varis, /indicator\("VARIS Zones"/);
assert.match(varis, /IAmTheLiquidity2/);
assert.match(varis, /payload = input\.string\("", "RS Levels Payload", display = display\.none\)/);
assert.match(varis, /chartFamilyInput = input\.string\("Auto", "Chart family"/);
assert.match(varis, /options = \["Auto", "ES", "NQ"\]/);
assert.match(varis, /manualRiskInterval = input\.float\(25\.0, "Manual Risk Interval \(Points\)"/);
assert.match(varis, /usePayloadRi = input\.bool\(true, "Use pasted RI when available"\)/);
assert.match(varis, /statValue\(levelText, "RI"\)/);
assert.match(varis, /riskInterval = usePayloadRi and not na\(payloadRiskInterval\) \? payloadRiskInterval : manualRiskInterval/);
assert.match(varis, /band1Points = riskInterval \* 0\.5/);
assert.match(varis, /band2Points = riskInterval/);
assert.match(varis, /hour\(time, "America\/New_York"\) == 18/);
assert.match(varis, /cumTPV/);
assert.match(varis, /vwapValue/);
assert.match(varis, /fill\(vwapPlot, upper1Plot/);
assert.match(varis, /fill\(vwapPlot, lower2Plot/);
assert.match(varis, /RSLEVELS/);
assert.match(varis, /array\.get\(parts, 1\) == "2"/);
assert.match(varis, /syminfo\.root/);
assert.match(varis, /syminfo\.tickerid/);
assert.doesNotMatch(varis, /\bstrategy\s*\(/i);
assert.doesNotMatch(varis, /\bstrategy\./i);
assert.doesNotMatch(varis, /\balertcondition\s*\(/i);
assert.doesNotMatch(varis, /\brequest\./i);

console.log('TradingView plugin tests passed');
