const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');

const pine = readFileSync(join(__dirname, '..', 'rs-levels.pine'), 'utf8');

assert.match(pine, /indicator\("RS Levels"/);
assert.doesNotMatch(pine, /\bstrategy\s*\(/i);
assert.doesNotMatch(pine, /\bstrategy\./i);
assert.doesNotMatch(pine, new RegExp('\\b' + 'ord' + 'er' + '\\b', 'i'));
assert.doesNotMatch(pine, /\balertcondition\s*\(/i);
assert.doesNotMatch(pine, /\brequest\./i);
assert.doesNotMatch(pine, /^\s*text\s*=/m);
assert.match(pine, /payload = input\.string\("", "RS Levels Payload", display = display\.none\)/);
assert.doesNotMatch(pine, /input\.text_area/);
assert.match(pine, /chartFamilyInput = input\.string\("Auto", "Chart family"/);
assert.match(pine, /options = \["Auto", "ES", "NQ"\]/);
assert.doesNotMatch(pine, /showStatus/);
assert.doesNotMatch(pine, /drawStatus/);
assert.doesNotMatch(pine, /statusText/);
assert.match(pine, /fontSizeInput = input\.string\("Small", "Font size"/);
assert.match(pine, /options = \["Tiny", "Small", "Normal", "Large", "Huge"\]/);
assert.match(pine, /labelSize/);
assert.match(pine, /"Tiny" => size\.tiny/);
assert.match(pine, /"Huge" => size\.huge/);
assert.match(pine, /size = labelSize\(\)/);
assert.match(pine, /displayLabelName/);
assert.match(pine, /str\.contains\(upperName, "OPEN"\)/);
assert.match(pine, /str\.replace_all\(cleaned, "Liquidity Map", ""\)/);
assert.match(pine, /labelText = displayLabelName\(name, kind\)/);
assert.match(pine, /labelBarsOffset/);
assert.match(pine, /labelVerticalOffset/);
assert.match(pine, /labelStackRows = 6/);
assert.match(pine, /labelStackColumnBars = 4/);
assert.match(pine, /labelDirection/);
assert.match(pine, /"mhp" => -1/);
assert.match(pine, /labelStackRow/);
assert.match(pine, /labelStackColumn/);
assert.match(pine, /labelX/);
assert.match(pine, /labelPrice/);
assert.match(pine, /labelY = labelPrice\(name, kind, price, labelIndex\)/);
assert.match(pine, /label\.new\(labelX\(labelIndex\), labelY,/);
assert.doesNotMatch(pine, /label\.new\(bar_index \+ labelBarsOffset, price,/);
assert.doesNotMatch(pine, /compactPayload/);
assert.match(pine, /RSLEVELS/);
assert.match(pine, /chartPayloadSymbol/);
assert.match(pine, /payloadCompact/);
assert.match(pine, /payloadSymbolLevelText/);
assert.match(pine, /str\.split\(payloadCompact\(payloadText\), "\|"\)/);
assert.match(pine, /array\.get\(parts, 0\) == "RSLEVELS"/);
assert.match(pine, /array\.get\(parts, 1\) == "2"/);
assert.match(pine, /for sectionIndex = 3 to array\.size\(parts\) - 3 by 3/);
assert.match(pine, /bestPayloadLevelText/);
assert.match(pine, /rootText == "NQ"/);
assert.match(pine, /rootText == "ES"/);
assert.match(pine, /str\.startswith\(tickerText, "MNQ"\)/);
assert.match(pine, /str\.startswith\(tickerText, "MES"\)/);
assert.match(pine, /str\.contains\(tickerIdText, ":NQ"\)/);
assert.match(pine, /str\.contains\(tickerIdText, ":ES"\)/);
assert.match(pine, /chartSymbol == "ES"/);
assert.match(pine, /chartSymbol == "NQ"/);
assert.match(pine, /esLevelText != "" and nqLevelText == ""/);
assert.match(pine, /levelTextForChart/);
assert.doesNotMatch(pine, /tradingview-bundle-json/);
assert.doesNotMatch(pine, /tradingview-json/);
assert.doesNotMatch(pine, /json/i);
assert.match(pine, /syminfo\.root/);
assert.match(pine, /syminfo\.tickerid/);
assert.match(pine, /syminfo\.description/);
assert.doesNotMatch(pine, /math\.abs\(price - close\)/);
assert.doesNotMatch(pine, /while sectionIndex \+ 2 < array\.size\(parts\)/);
assert.doesNotMatch(pine, /fallbackSymbol/);
assert.match(pine, /str\.split/);
assert.match(pine, /showDdBands/);
assert.match(pine, /showHp/);
assert.match(pine, /showBullZones/);
assert.match(pine, /showBearZones/);
assert.match(pine, /showZoneFills = input\.bool\(true, "Zone fills"\)/);
assert.doesNotMatch(pine, /showUnknown/);
assert.match(pine, /zoneFillOpacityInput = input\.int\(12, "Zone fill opacity %"/);
assert.match(pine, /ddBandColorInput = input\.color\(color\.rgb\(41, 182, 246\), "", inline = "dd"\)/);
assert.match(pine, /showDdBands = input\.bool\(true, "DD bands", inline = "dd"\)/);
assert.match(pine, /hpColorInput = input\.color\(color\.rgb\(41, 98, 255\), "", inline = "hp"\)/);
assert.match(pine, /showHp = input\.bool\(true, "HP", inline = "hp"\)/);
assert.match(pine, /mhpColorInput = input\.color\(color\.rgb\(255, 152, 0\), "", inline = "mhp"\)/);
assert.match(pine, /showMhp = input\.bool\(true, "MHP", inline = "mhp"\)/);
assert.match(pine, /openCloseColorInput = input\.color\(color\.rgb\(224, 224, 224\), "", inline = "openClose"\)/);
assert.match(pine, /showOpenClose = input\.bool\(true, "Open\/close", inline = "openClose"\)/);
assert.match(pine, /referenceColorInput = input\.color\(color\.rgb\(255, 235, 59\), "", inline = "reference"\)/);
assert.match(pine, /showReference = input\.bool\(true, "References", inline = "reference"\)/);
assert.match(pine, /genericZoneColorInput = input\.color\(color\.rgb\(76, 175, 80\), "", inline = "zone"\)/);
assert.match(pine, /showZones = input\.bool\(true, "Zones", inline = "zone"\)/);
assert.match(pine, /bullZoneColorInput = input\.color\(color\.rgb\(76, 175, 80\), "", inline = "bullZone"\)/);
assert.match(pine, /showBullZones = input\.bool\(true, "Bull zones", inline = "bullZone"\)/);
assert.match(pine, /bearZoneColorInput = input\.color\(color\.rgb\(240, 98, 146\), "", inline = "bearZone"\)/);
assert.match(pine, /showBearZones = input\.bool\(true, "Bear zones", inline = "bearZone"\)/);
assert.match(pine, /otherLevelColorInput = input\.color\(color\.rgb\(158, 158, 158\), "", inline = "otherLevels"\)/);
assert.match(pine, /showOtherLevels = input\.bool\(true, "Other levels", inline = "otherLevels"\)/);
assert.match(pine, /ddBandColorInput[\s\S]*showDdBands/);
assert.match(pine, /hpColorInput[\s\S]*showHp/);
assert.match(pine, /bearZoneColorInput[\s\S]*showBearZones/);
assert.doesNotMatch(pine, /group = "Level colors"/);
assert.doesNotMatch(pine, /unknownColorInput/);
assert.match(pine, /"zone-bull"/);
assert.match(pine, /"zone-bear"/);
assert.match(pine, /"zone-bull" => bullZoneColorInput/);
assert.match(pine, /"zone-bear" => bearZoneColorInput/);
assert.match(pine, /"hp" => hpColorInput/);
assert.match(pine, /=> otherLevelColorInput/);
assert.match(pine, /=> showOtherLevels/);
assert.match(pine, /max_boxes_count = 500/);
assert.match(pine, /array\.new_box\(\)/);
assert.match(pine, /box\.delete\(array\.pop\(rsBoxes\)\)/);
assert.match(pine, /zoneBoundarySide/);
assert.match(pine, /str\.contains\(upperName, "BZT"\)/);
assert.match(pine, /str\.contains\(upperName, "BRZB"\)/);
assert.match(pine, /drawZoneFill/);
assert.match(pine, /drawZoneFills\(levelText, maxCount\)/);
assert.match(pine, /box\.new\(left = bar_index - 1/);
assert.match(pine, /bgcolor = color\.new\(zoneColor, fillTransparency\)/);
assert.match(pine, /lineStyleInput/);
assert.match(pine, /maxLevelsInput/);
assert.match(pine, /max_lines_count = 500/);
assert.match(pine, /max_labels_count = 500/);
assert.match(pine, /maxval = 500/);
assert.doesNotMatch(pine, /label\.style_label_down/);

console.log('TradingView plugin tests passed');
